# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Secure Systems Lab'
#tagline:          'Laboriously Securing Systems'
description:      'Laboriously Securing Systems'
url:              https://ssl.engineering.nyu.edu
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

#paginate:         5

# Custom vars
version:

github:
  repo:

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
