# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Secure Systems Lab'
description:      'Laboriously Securing Systems'
url:              https://ssl.engineering.nyu.edu
baseurl:          /ssl-site/

#author:
#  name:           'ssl'
#  url:            https://ssl.engineering.nyu.edu

#paginate:         5

sass:
  sass_dir: _sass

# Custom vars
version:

github:
  repo:

gems:
  - jekyll-paginate
  - jekyll-gist
