url: https://ssl.engineering.nyu.edu
baseurl: /
permalink: /blog/:year-:month-:day-:title
highlighter: rouge
sass:
    sass_dir: _sass
avatar: /img/ssl_lock.png
disqus-shortname: secure-systems-lab
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git', 'vendor']
plugins:
  - 'jekyll-feed'
